SELECT PNUM, COLOR, WEIGHT FROM Parts ORDER BY WEIGHT DESC;

SELECT MAX(WEIGHT) AS WEIGHT FROM Parts;

SELECT sum(Qty), SNUM FROM Shipment
GROUP BY SNUM;

SELECT sum(Qty), SNUM FROM Shipment
GROUP BY SNUM;